## Deliverable 2. Create a Customer Travel Destinations Map.

In [38]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

g_key = "AIzaSyAzAxfoF8wGLWKi1zZQGkNfJQTrJo5fJ4E"

from config import weather_api_key

# Import API key
# from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [9]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Butaritari,KI,3.0707,172.7902,80.91,80,99,10.85,light rain
1,1,New Norfolk,AU,-42.7826,147.0587,43.92,87,23,1.01,few clouds
2,2,Torbay,CA,47.6666,-52.7314,63.37,34,20,6.91,few clouds
3,3,Albany,US,42.6001,-73.9662,91.67,54,0,5.01,clear sky
4,4,Lompoc,US,34.6391,-120.4579,76.78,58,0,12.66,clear sky

In [14]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your vacation?"))
max_temp = float(input("What is the maximum temperature you would like for your vacation?"))

What is the minimum temperature you would like for your vacation?60
What is the maximum temperature you would like for your vacation?90

In [19]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp)& (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Butaritari,KI,3.0707,172.7902,80.91,80,99,10.85,light rain
2,2,Torbay,CA,47.6666,-52.7314,63.37,34,20,6.91,few clouds
4,4,Lompoc,US,34.6391,-120.4579,76.78,58,0,12.66,clear sky
8,8,Ponta Do Sol,PT,32.6667,-17.1000,70.43,82,22,2.42,few clouds
9,9,Jamestown,US,42.0970,-79.2353,83.84,57,0,12.66,clear sky
10,10,Rikitea,PF,-23.1203,-134.9692,75.22,74,10,6.80,clear sky
11,11,Caravelas,BR,-17.7125,-39.2481,75.29,63,2,8.57,clear sky
12,12,Puerto Ayora,EC,-0.7393,-90.3518,76.96,90,80,5.99,broken clouds
14,14,Ponta Delgada,PT,37.7333,-25.6667,65.12,100,100,5.75,fog
15,15,Kitimat,CA,54.0524,-128.6534,65.91,46,1,1.05,clear sky

In [20]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                348
City                   348
Country                348
Lat                    348
Lng                    348
Max Temp               348
Humidity               348
Cloudiness             348
Wind Speed             348
Current Description    348
dtype: int64

In [22]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
# N/A df does not have empty rows

In [24]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Butaritari,KI,80.91,light rain,3.0707,172.7902,
2,Torbay,CA,63.37,few clouds,47.6666,-52.7314,
4,Lompoc,US,76.78,clear sky,34.6391,-120.4579,
8,Ponta Do Sol,PT,70.43,few clouds,32.6667,-17.1000,
9,Jamestown,US,83.84,clear sky,42.0970,-79.2353,
10,Rikitea,PF,75.22,clear sky,-23.1203,-134.9692,
11,Caravelas,BR,75.29,clear sky,-17.7125,-39.2481,
12,Puerto Ayora,EC,76.96,broken clouds,-0.7393,-90.3518,
14,Ponta Delgada,PT,65.12,fog,37.7333,-25.6667,
15,Kitimat,CA,65.91,clear sky,54.0524,-128.6534,

In [39]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    # 6c. Get latitude and longitude from DataFrame
    params["location"]: f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    #except (IndexError):
        #print("Hotel not found...skipping.")
    except BaseException as err: 
        print(err)

list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range

KeyboardInterrupt:

In [29]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df[hotel_df["Hotel Name"]!= '']
clean_hotel_df.head(10)

Empty DataFrame
Columns: [City, Country, Max Temp, Current Description, Lat, Lng, Hotel Name]
Index: []

In [30]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [31]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [40]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))